from typing import Tuple

# =========================
# Vector3D
# =========================
class Vector3D:
    def __init__(self, x: float, y: float, z: float) -> None: ...

    def x(self) -> float: ...
    def setX(self, x: float) -> None: ...

    def y(self) -> float: ...
    def setY(self, y: float) -> None: ...

    def z(self) -> float: ...
    def setZ(self, z: float) -> None: ...

    def norm(self) -> float: ...

    def __add__(self, other: 'Vector3D') -> 'Vector3D': ...

    def __iadd__(self, other: 'Vector3D') -> 'Vector3D': ...

    def __sub__(self, other: 'Vector3D') -> 'Vector3D': ...

    def __isub__(self, other: 'Vector3D') -> 'Vector3D': ...

    def __mul__(self, scalar: float) -> 'Vector3D': ...

    def __imul__(self, scalar: float) -> 'Vector3D': ...

    def dot(self, other: 'Vector3D') -> float: ...

    def cross(self, other: 'Vector3D') -> 'Vector3D': ...

    def __truediv__(self, scalar: float) -> 'Vector3D': ...

    def __itruediv__(self, scalar: float) -> 'Vector3D': ...

    def __neg__(self) -> 'Vector3D': ...

    def __iter__(self) -> Tuple[float, float, float]: ...


# =========================
# Quaternion
# =========================
class Quaternion:
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...

    def x(self) -> float: ...
    def setX(self, x: float) -> None: ...

    def y(self) -> float: ...
    def setY(self, y: float) -> None: ...

    def z(self) -> float: ...
    def setZ(self, z: float) -> None: ...

    def w(self) -> float: ...
    def setW(self, w: float) -> None: ...


# =========================
# State
# =========================
class State_py:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...

    # -------------------------
    # Getters
    # -------------------------

    def posEcf(self) -> Vector3D: ...

    def velEcf(self) -> Vector3D: ...

    def qbn(self) -> Quaternion: ...

    def wnbB(self) -> Vector3D: ...

    def accB(self) -> Vector3D: ...

    def rudder(self) -> Vector3D: ...

    def stage(self) -> float: ...


# =========================
# CoordinateHelper
# =========================
class CoordinateHelper:
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...

    @staticmethod
    def ecefToLla_py(ecef_pos: Vector3D) -> Vector3D: ...

    @staticmethod
    def llaToEcef_py(lla_pos: Vector3D) -> Vector3D: ...

    # -------------------------
    # NUE <-> ECEF
    # -------------------------
    @staticmethod
    def nueToEcefPosition_py(
            nue_pos: Vector3D,
            lon: float,
            lat: float
    ) -> Vector3D: ...

    @staticmethod
    def ecefToNuePosition_py(
            ecef_pos: Vector3D,
            lon: float,
            lat: float
    ) -> Vector3D: ...

    @staticmethod
    def nueToEcefVelocity_py(
            nue_vel: Vector3D,
            lon: float,
            lat: float
    ) -> Vector3D: ...

    @staticmethod
    def ecefToNueVelocity_py(
            ecef_vel: Vector3D,
            lon: float,
            lat: float
    ) -> Vector3D: ...

    # -------------------------
    # Body <-> NUE
    # -------------------------
    @staticmethod
    def bodyToNueVelocity_py(
            body_vel: Vector3D,
            qbn: Quaternion
    ) -> Vector3D: ...

    @staticmethod
    def nueToBodyVelocity_py(
            nue_vel: Vector3D,
            qbn: Quaternion
    ) -> Vector3D: ...

    # -------------------------
    # Euler <-> Quaternion
    # -------------------------
    @staticmethod
    def euler231ToQuaternion_py(
            yaw: float,
            pitch: float,
            roll: float
    ) -> Quaternion: ...

    @staticmethod
    def quaternionToEuler231_py(
            qbn: Quaternion
    ) -> Vector3D: ...

    # -------------------------
    # Attitude angles
    # -------------------------
    @staticmethod
    def getTheta_py(vec_nue: Vector3D) -> float: ...

    @staticmethod
    def getPsi_py(vec_nue: Vector3D) -> float: ...

    @staticmethod
    def is_geometrically_visible(a_pos_x: float,a_pos_y: float,a_pos_z: float,b_pos_x: float,b_pos_y: float,b_pos_z: float, max_range:float, ignore_z:bool=False)-> bool:...