# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _UtilsPy
else:
    import _UtilsPy

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Vector3D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _UtilsPy.Vector3D_swiginit(self, _UtilsPy.new_Vector3D(*args))
    __swig_destroy__ = _UtilsPy.delete_Vector3D

    def x(self):
        return _UtilsPy.Vector3D_x(self)

    def setX(self, x):
        return _UtilsPy.Vector3D_setX(self, x)

    def y(self):
        return _UtilsPy.Vector3D_y(self)

    def setY(self, y):
        return _UtilsPy.Vector3D_setY(self, y)

    def z(self):
        return _UtilsPy.Vector3D_z(self)

    def setZ(self, z):
        return _UtilsPy.Vector3D_setZ(self, z)

    def norm(self):
        return _UtilsPy.Vector3D_norm(self)

    def __add__(self, other):
        return _UtilsPy.Vector3D___add__(self, other)

    def __iadd__(self, other):
        return _UtilsPy.Vector3D___iadd__(self, other)

    def __sub__(self, other):
        return _UtilsPy.Vector3D___sub__(self, other)

    def __isub__(self, other):
        return _UtilsPy.Vector3D___isub__(self, other)

    def __mul__(self, scalar):
        return _UtilsPy.Vector3D___mul__(self, scalar)

    def __imul__(self, scalar):
        return _UtilsPy.Vector3D___imul__(self, scalar)

    def dot(self, other):
        return _UtilsPy.Vector3D_dot(self, other)

    def cross(self, other):
        return _UtilsPy.Vector3D_cross(self, other)

    def __truediv__(self, *args):
        return _UtilsPy.Vector3D___truediv__(self, *args)
    __div__ = __truediv__



    def __itruediv__(self, *args):
        return _UtilsPy.Vector3D___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __neg__(self):
        return _UtilsPy.Vector3D___neg__(self)

# Register Vector3D in _UtilsPy:
_UtilsPy.Vector3D_swigregister(Vector3D)
class Quaternion(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _UtilsPy.delete_Quaternion

    def __init__(self, *args):
        _UtilsPy.Quaternion_swiginit(self, _UtilsPy.new_Quaternion(*args))

    def x(self):
        return _UtilsPy.Quaternion_x(self)

    def setX(self, x):
        return _UtilsPy.Quaternion_setX(self, x)

    def y(self):
        return _UtilsPy.Quaternion_y(self)

    def setY(self, y):
        return _UtilsPy.Quaternion_setY(self, y)

    def z(self):
        return _UtilsPy.Quaternion_z(self)

    def setZ(self, z):
        return _UtilsPy.Quaternion_setZ(self, z)

    def w(self):
        return _UtilsPy.Quaternion_w(self)

    def setW(self, w):
        return _UtilsPy.Quaternion_setW(self, w)

# Register Quaternion in _UtilsPy:
_UtilsPy.Quaternion_swigregister(Quaternion)
class State_py(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _UtilsPy.State_py_swiginit(self, _UtilsPy.new_State_py())
    __swig_destroy__ = _UtilsPy.delete_State_py

    def posEcf(self):
        return _UtilsPy.State_py_posEcf(self)

    def velEcf(self):
        return _UtilsPy.State_py_velEcf(self)

    def qbn(self):
        return _UtilsPy.State_py_qbn(self)

    def wnbB(self):
        return _UtilsPy.State_py_wnbB(self)

    def accB(self):
        return _UtilsPy.State_py_accB(self)

    def rudder(self):
        return _UtilsPy.State_py_rudder(self)

    def stage(self):
        return _UtilsPy.State_py_stage(self)

# Register State_py in _UtilsPy:
_UtilsPy.State_py_swigregister(State_py)
class CoordinateHelper(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _UtilsPy.CoordinateHelper_swiginit(self, _UtilsPy.new_CoordinateHelper())
    __swig_destroy__ = _UtilsPy.delete_CoordinateHelper

    @staticmethod
    def ecefToLla_py(ecef_pos):
        return _UtilsPy.CoordinateHelper_ecefToLla_py(ecef_pos)

    @staticmethod
    def llaToEcef_py(lla):
        return _UtilsPy.CoordinateHelper_llaToEcef_py(lla)

    @staticmethod
    def nueToEcefPosition_py(nue_pos, lon, lat):
        return _UtilsPy.CoordinateHelper_nueToEcefPosition_py(nue_pos, lon, lat)

    @staticmethod
    def ecefToNuePosition_py(ecef_pos, lon, lat):
        return _UtilsPy.CoordinateHelper_ecefToNuePosition_py(ecef_pos, lon, lat)

    @staticmethod
    def nueToEcefVelocity_py(nue_vel, lon, lat):
        return _UtilsPy.CoordinateHelper_nueToEcefVelocity_py(nue_vel, lon, lat)

    @staticmethod
    def ecefToNueVelocity_py(ecef_vel, lon, lat):
        return _UtilsPy.CoordinateHelper_ecefToNueVelocity_py(ecef_vel, lon, lat)

    @staticmethod
    def bodyToNueVelocity_py(body_vel, qbn):
        return _UtilsPy.CoordinateHelper_bodyToNueVelocity_py(body_vel, qbn)

    @staticmethod
    def nueToBodyVelocity_py(nue_vel, qbn):
        return _UtilsPy.CoordinateHelper_nueToBodyVelocity_py(nue_vel, qbn)

    @staticmethod
    def euler231ToQuaternion_py(yaw, pitch, roll):
        return _UtilsPy.CoordinateHelper_euler231ToQuaternion_py(yaw, pitch, roll)

    @staticmethod
    def quaternionToEuler231_py(qbn):
        return _UtilsPy.CoordinateHelper_quaternionToEuler231_py(qbn)

    @staticmethod
    def getTheta_py(vec_nue):
        return _UtilsPy.CoordinateHelper_getTheta_py(vec_nue)

    @staticmethod
    def getPsi_py(vec_nue):
        return _UtilsPy.CoordinateHelper_getPsi_py(vec_nue)

    @staticmethod
    def is_geometrically_visible(a_pos_x, a_pos_y, a_pos_z, b_pos_x, b_pos_y, b_pos_z, max_range, ignore_z=False):
        return _UtilsPy.CoordinateHelper_is_geometrically_visible(a_pos_x, a_pos_y, a_pos_z, b_pos_x, b_pos_y, b_pos_z, max_range, ignore_z)

# Register CoordinateHelper in _UtilsPy:
_UtilsPy.CoordinateHelper_swigregister(CoordinateHelper)

