# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _CompCruiseMissilePy
else:
    import _CompCruiseMissilePy

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CompCruiseMissilePy.delete_SwigPyIterator

    def value(self):
        return _CompCruiseMissilePy.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _CompCruiseMissilePy.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _CompCruiseMissilePy.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _CompCruiseMissilePy.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _CompCruiseMissilePy.SwigPyIterator_equal(self, x)

    def copy(self):
        return _CompCruiseMissilePy.SwigPyIterator_copy(self)

    def next(self):
        return _CompCruiseMissilePy.SwigPyIterator_next(self)

    def __next__(self):
        return _CompCruiseMissilePy.SwigPyIterator___next__(self)

    def previous(self):
        return _CompCruiseMissilePy.SwigPyIterator_previous(self)

    def advance(self, n):
        return _CompCruiseMissilePy.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _CompCruiseMissilePy.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _CompCruiseMissilePy.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _CompCruiseMissilePy.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _CompCruiseMissilePy.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _CompCruiseMissilePy.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _CompCruiseMissilePy.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _CompCruiseMissilePy:
_CompCruiseMissilePy.SwigPyIterator_swigregister(SwigPyIterator)
class Vector3dL(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _CompCruiseMissilePy.Vector3dL_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CompCruiseMissilePy.Vector3dL___nonzero__(self)

    def __bool__(self):
        return _CompCruiseMissilePy.Vector3dL___bool__(self)

    def __len__(self):
        return _CompCruiseMissilePy.Vector3dL___len__(self)

    def __getslice__(self, i, j):
        return _CompCruiseMissilePy.Vector3dL___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CompCruiseMissilePy.Vector3dL___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CompCruiseMissilePy.Vector3dL___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CompCruiseMissilePy.Vector3dL___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CompCruiseMissilePy.Vector3dL___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CompCruiseMissilePy.Vector3dL___setitem__(self, *args)

    def pop(self):
        return _CompCruiseMissilePy.Vector3dL_pop(self)

    def append(self, x):
        return _CompCruiseMissilePy.Vector3dL_append(self, x)

    def empty(self):
        return _CompCruiseMissilePy.Vector3dL_empty(self)

    def size(self):
        return _CompCruiseMissilePy.Vector3dL_size(self)

    def swap(self, v):
        return _CompCruiseMissilePy.Vector3dL_swap(self, v)

    def begin(self):
        return _CompCruiseMissilePy.Vector3dL_begin(self)

    def end(self):
        return _CompCruiseMissilePy.Vector3dL_end(self)

    def rbegin(self):
        return _CompCruiseMissilePy.Vector3dL_rbegin(self)

    def rend(self):
        return _CompCruiseMissilePy.Vector3dL_rend(self)

    def clear(self):
        return _CompCruiseMissilePy.Vector3dL_clear(self)

    def get_allocator(self):
        return _CompCruiseMissilePy.Vector3dL_get_allocator(self)

    def pop_back(self):
        return _CompCruiseMissilePy.Vector3dL_pop_back(self)

    def erase(self, *args):
        return _CompCruiseMissilePy.Vector3dL_erase(self, *args)

    def __init__(self, *args):
        _CompCruiseMissilePy.Vector3dL_swiginit(self, _CompCruiseMissilePy.new_Vector3dL(*args))

    def push_back(self, x):
        return _CompCruiseMissilePy.Vector3dL_push_back(self, x)

    def front(self):
        return _CompCruiseMissilePy.Vector3dL_front(self)

    def back(self):
        return _CompCruiseMissilePy.Vector3dL_back(self)

    def assign(self, n, x):
        return _CompCruiseMissilePy.Vector3dL_assign(self, n, x)

    def resize(self, *args):
        return _CompCruiseMissilePy.Vector3dL_resize(self, *args)

    def insert(self, *args):
        return _CompCruiseMissilePy.Vector3dL_insert(self, *args)

    def reserve(self, n):
        return _CompCruiseMissilePy.Vector3dL_reserve(self, n)

    def capacity(self):
        return _CompCruiseMissilePy.Vector3dL_capacity(self)
    __swig_destroy__ = _CompCruiseMissilePy.delete_Vector3dL

# Register Vector3dL in _CompCruiseMissilePy:
_CompCruiseMissilePy.Vector3dL_swigregister(Vector3dL)
class Missile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _CompCruiseMissilePy.Missile_swiginit(self, _CompCruiseMissilePy.new_Missile())
    __swig_destroy__ = _CompCruiseMissilePy.delete_Missile

    def Save(self, flag):
        return _CompCruiseMissilePy.Missile_Save(self, flag)

    def Init(self, step, m_lla, maxLoad):
        return _CompCruiseMissilePy.Missile_Init(self, step, m_lla, maxLoad)

    def Launch(self, t_lla):
        return _CompCruiseMissilePy.Missile_Launch(self, t_lla)

    def SetDesiredHeight(self, height):
        return _CompCruiseMissilePy.Missile_SetDesiredHeight(self, height)

    def SetDesiredSpeed(self, speed):
        return _CompCruiseMissilePy.Missile_SetDesiredSpeed(self, speed)

    def SetDesiredAccZ(self, accZ):
        return _CompCruiseMissilePy.Missile_SetDesiredAccZ(self, accZ)

    def SetTargetEcf(self, targetPosEcf, targetVelEcf):
        return _CompCruiseMissilePy.Missile_SetTargetEcf(self, targetPosEcf, targetVelEcf)

    def update(self):
        return _CompCruiseMissilePy.Missile_update(self)

    def getState(self):
        return _CompCruiseMissilePy.Missile_getState(self)

# Register Missile in _CompCruiseMissilePy:
_CompCruiseMissilePy.Missile_swigregister(Missile)

